In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('us-dealers-used.csv')

/var/folders/7b/trlfgd_d5gv_jv53bccbf7rw0000gn/T/ipykernel_57823/4071429681.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('us-dealers-used.csv')

In [3]:
df.head()

,id,vin,price,miles,stock_no,year,make,model,trim,body_type,...,drivetrain,transmission,fuel_type,engine_size,engine_block,seller_name,street,city,state,zip
0,38b2f52e-8f5d,1GCWGFCF3F1284719,20998.0,115879.0,W1T503168C,2015.0,Chevrolet,Express Cargo,Work Van,Cargo Van,...,RWD,Automatic,E85 / Unleaded,4.8,V,nissan ellicott city,8569 Baltimore National Pike,Ellicott City,MD,21043
1,97ba4955-ccf0,WBY7Z8C59JVB87514,27921.0,7339.0,P33243,2018.0,BMW,i3,s,Hatchback,...,RWD,Automatic,Electric / Premium Unleaded,0.6,I,hendrick honda pompano beach,5381 N Federal Highway,Pompano Beach,FL,33064
2,be1da9fd-0f34,ML32F4FJ2JHF10325,11055.0,39798.0,WM2091A,2018.0,Mitsubishi,Mirage G4,SE,Sedan,...,FWD,Automatic,Unleaded,1.2,I,russ darrow toyota,2700 West Washington St.,West Bend,WI,53095
3,84327e45-6cb6,1GCPTEE15K1291189,52997.0,28568.0,9U2Y425A,2019.0,Chevrolet,Colorado,ZR2,Pickup,...,4WD,Automatic,Diesel,2.8,I,young kia,308 North Main Street,Layton,UT,84041
4,cde691c3-91dd,1G2AL18F087312093,NaN,188485.0,T36625A,2008.0,Pontiac,G5,Base,Coupe,...,FWD,Automatic,Unleaded,2.2,I,pappas toyota,10011 Spencer Rd,Saint Peters,MO,63376

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7104304 entries, 0 to 7104303
Data columns (total 21 columns):
 #   Column        Dtype
---  ------        -----
 0   id            object
 1   vin           object
 2   price         float64
 3   miles         float64
 4   stock_no      object
 5   year          float64
 6   make          object
 7   model         object
 8   trim          object
 9   body_type     object
 10  vehicle_type  object
 11  drivetrain    object
 12  transmission  object
 13  fuel_type     object
 14  engine_size   float64
 15  engine_block  object
 16  seller_name   object
 17  street        object
 18  city          object
 19  state         object
 20  zip           object
dtypes: float64(4), object(17)
memory usage: 1.1+ GB

In [5]:
pd.set_option('display.max_rows', None)

make_counts = df['make'].value_counts()
make_counts

make
Ford             933834
Chevrolet        815351
Toyota           647263
Honda            516484
Nissan           451098
Jeep             433401
BMW              270940
Hyundai          268377
GMC              256735
Mercedes-Benz    227486
Kia              226792
RAM              211684
Dodge            205920
Subaru           190266
Lexus            179314
Volkswagen       159730
Audi             128078
Mazda            111099
Cadillac         102680
Acura             99906
Buick             92328
INFINITI          83252
Chrysler          79927
Lincoln           66740
Land Rover        63629
Volvo             52264
Porsche           40292
MINI              37294
Mitsubishi        32919
Jaguar            26907
Alfa Romeo        10488
Maserati           9641
GENESIS            8704
Scion              8022
Pontiac            8019
FIAT               7184
Tesla              7139
Mercury            4637
Saturn             4501
Bentley            4193
Ferrari            3781
Hummer             2779
Suzuki             1976
Aston Martin       1796
Rolls-Royce        1645
smart              1427
Lamborghini        1423
Isuzu              1201
McLaren            1196
Saab                946
Oldsmobile          642
Plymouth            244
KARMA               160
Lotus               142
Am General          121
Eagle               118
Geo                  55
Fisker               52
Maybach              23
Bugatti              23
Sterling             22
Datsun                7
Daewoo                3
Peugeot               2
Panoz                 1
AMC                   1
Name: count, dtype: int64

In [6]:
df_tesla = df[df['make'].str.lower() == 'tesla'].copy()

In [7]:
df_tesla['transmission'] = df_tesla['transmission'].fillna('Automatic')
df_tesla['fuel_type'] = df_tesla['fuel_type'].fillna('Electric')
df_tesla['engine_block'] = df_tesla['engine_block'].fillna('E')
df_tesla['engine_size'] = df_tesla['engine_size'].fillna('E')

In [8]:
df_tesla.dropna(inplace=True)

In [9]:
df.dropna(inplace=True)

In [10]:
# Convert `miles` and `year` columns to integer
df['miles'] = df['miles'].astype(int)
df['year'] = df['year'].astype(int)

In [11]:
# Drop specified columns
columns_to_drop = ['id', 'vin', 'stock_no', 'seller_name','street']
df.drop(columns=columns_to_drop, inplace=True)

In [12]:
df.shape[0]

6167605

In [13]:
df_filtered = df[df['year'] >= 2017]

In [14]:
# Filter the DataFrame to keep only rows where `miles` is less than or equal to 300000
df_filtered = df[df['miles'] <= 300000]

In [15]:
makes_to_drop = make_counts[make_counts < 10489].index

In [16]:
# List of all US states
us_states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']

In [17]:
# Filter out non-US states
df_filtered = df_filtered[df_filtered['state'].isin(us_states)]

In [18]:
df_filtered = df_filtered[~df_filtered['make'].isin(makes_to_drop)]

In [19]:
df_filtered = pd.concat([df_filtered, df_tesla], ignore_index=True)

In [20]:
df_sampled = df_filtered.sample(n=150000, random_state=42)

In [21]:
df_sampled.head(25)

,price,miles,year,make,model,trim,body_type,vehicle_type,drivetrain,transmission,...,engine_size,engine_block,city,state,zip,id,vin,stock_no,seller_name,street
5775958,24987.0,101328.0,2017.0,Jeep,All-New Wrangler Unlimited,Sport,SUV,Truck,4WD,Manual,...,3.6,V,Carrollton,GA,30117,NaN,NaN,NaN,NaN,NaN
5650569,13694.0,107999.0,2013.0,Ford,Edge,Limited,Crossover,Truck,FWD,Automatic,...,3.5,V,Orange City,FL,32763,NaN,NaN,NaN,NaN,NaN
5094670,20829.0,29745.0,2018.0,Ford,Escape,SE,SUV,Truck,4WD,Automatic,...,1.5,I,Orchard Park,NY,14127,NaN,NaN,NaN,NaN,NaN
4934478,16595.0,65770.0,2014.0,BMW,X1,35i,SUV,Car,4WD,Automatic,...,3.0,I,Carson City,NV,89701,NaN,NaN,NaN,NaN,NaN
1793254,19643.0,22036.0,2018.0,Volkswagen,Tiguan,S,SUV,Truck,4WD,Automatic,...,2.0,I,Merrimack,NH,03054,NaN,NaN,NaN,NaN,NaN
2386763,21988.0,5628.0,2020.0,Toyota,Camry,LE,Sedan,Car,FWD,Automatic,...,2.5,I,Owings Mills,MD,21117,NaN,NaN,NaN,NaN,NaN
1270784,28896.0,26604.0,2019.0,Chevrolet,Traverse,1LT,SUV,Truck,FWD,Automatic,...,3.6,V,Lansing,MI,48912,NaN,NaN,NaN,NaN,NaN
3461751,25987.0,8849.0,2019.0,Ford,F-150,XLT,Pickup,Truck,RWD,Automatic,...,5.0,V,Johnsbury,VT,05819,NaN,NaN,NaN,NaN,NaN
1539656,94469.0,9970.0,2020.0,BMW,M5,Base,Sedan,Car,4WD,Automatic,...,4.4,V,Louisville,KY,40216,NaN,NaN,NaN,NaN,NaN
665948,25949.0,18696.0,2019.0,Acura,TLX,Base,Sedan,Car,FWD,Automatic,...,2.4,I,Cary,NC,27511,NaN,NaN,NaN,NaN,NaN
5195458,14000.0,37924.0,2018.0,Nissan,Sentra,SV,Sedan,Car,FWD,Automatic,...,1.8,I,Florence,KY,41042,NaN,NaN,NaN,NaN,NaN
10446,21888.0,17079.0,2004.0,Ford,Thunderbird,Deluxe,Convertible,Car,RWD,Automatic,...,3.9,V,Fort Atkinson,WI,53538,NaN,NaN,NaN,NaN,NaN
76146,9889.0,90707.0,2014.0,Buick,Regal,Base,Sedan,Car,FWD,Automatic,...,2.0,I,Doylestown,PA,18902,NaN,NaN,NaN,NaN,NaN
5395589,34300.0,651.0,2021.0,Toyota,RAV4,Limited,SUV,Truck,4WD,Automatic,...,2.5,I,Fallston,MD,21047,NaN,NaN,NaN,NaN,NaN
5453259,17235.0,38138.0,2018.0,Nissan,Rogue,S,Crossover,Truck,4WD,Automatic,...,2.5,I,Hackensack,NJ,07601,NaN,NaN,NaN,NaN,NaN
3645916,18950.0,44085.0,2017.0,Toyota,Prius,Two,Hatchback,Car,FWD,Automatic,...,1.8,I,Pearl,MS,39208,NaN,NaN,NaN,NaN,NaN
2933853,37899.0,40174.0,2018.0,Chevrolet,Silverado 1500,LT,Pickup,Truck,4WD,Automatic,...,5.3,V,Shelby,NC,28152,NaN,NaN,NaN,NaN,NaN
4046858,21484.0,68640.0,2015.0,Acura,TLX,Technology Package,Sedan,Car,FWD,Automatic,...,3.5,V,Lincoln,NE,68521,NaN,NaN,NaN,NaN,NaN
839177,13460.0,132952.0,2014.0,Toyota,RAV4,LE,SUV,Truck,FWD,Automatic,...,2.5,I,Houston,TX,77054,NaN,NaN,NaN,NaN,NaN
4313077,27625.0,37990.0,2019.0,Dodge,Charger,SXT,Sedan,Car,RWD,Automatic,...,3.6,V,Columbia,SC,29210,NaN,NaN,NaN,NaN,NaN
5448399,21868.0,14182.0,2020.0,Nissan,Rogue,SV,Crossover,Truck,FWD,Automatic,...,2.5,I,Cumming,GA,30040,NaN,NaN,NaN,NaN,NaN
961147,26838.0,55308.0,2017.0,Jeep,Cherokee,Overland,SUV,Truck,FWD,Automatic,...,3.2,V,Coconut Creek,FL,33073,NaN,NaN,NaN,NaN,NaN
6041438,38919.0,11049.0,2020.0,RAM,Ram 1500 Pickup,Big Horn/Lone Star,Pickup,Truck,RWD,Automatic,...,5.7,V,Winder,GA,30680,NaN,NaN,NaN,NaN,NaN
3513967,14997.0,40871.0,2017.0,Volkswagen,Jetta,S,Sedan,Car,FWD,Manual,...,1.4,I,Tilton,NH,03276,NaN,NaN,NaN,NaN,NaN
5310623,20988.0,31808.0,2018.0,Jeep,Compass,Latitude,SUV,Truck,4WD,Manual,...,2.4,I,Greensburg,PA,15601.0,NaN,NaN,NaN,NaN,NaN

In [22]:
df_sampled.to_csv('used_clean.csv', index=False)